version: '3.1'

services:
  db:
    build: ./db
    container_name: db
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=238ska8e2
      - MYSQL_DATABASE=sp5
      - MYSQL_USER=sp5
      - MYSQL_PASSWORD=srSI49is0ksdslewiE
      - MYSQL_INITDB_SKIP_TZINFO=yes
    volumes: 
      - db-sp5:/var/lib/mysql:rw
      - /tmp:/tmp
    ports:
      - "3391:3306"
  backend:
    build: .
    container_name: backend
    restart: always
    hostname: sp5_backend
    logging:
      driver: json-file
    cap_add:
       - SYS_PTRACE
    volumes:
      - /var/www/html/sp5:/app
      - /etc/hosts:/etc/hosts
      - /tmp:/tmp
      - /var/www/html/sp5_nginx:/etc/nginx/conf.d
      - /var/www/html/sp5_supervisor:/etc/supervisor/conf.d
    ports:
      - 5003:80
      - "6003:22"
    dns:
      - "8.8.8.8"
    networks:
      vpsp5_backend:
        ipv4_address: "172.40.0.2"
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      vpsp5_backend:
        ipv4_address: "172.40.0.3"
volumes: 
  db-sp5: {}
networks:
  vpsp5_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
