version: '3.7'

services:
  db:
    build: ./db
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=sql@Paco24#
      - MYSQL_DATABASE=crud_db
      - MYSQL_USER=crud_user
      - MYSQL_PASSWORD=crud@Paco24#
      - MYSQL_INITDB_SKIP_TZINFO=yes
    volumes: 
      - crud:/var/lib/mysql
    ports:
      - "3391:3306"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    hostname: crud
    logging:
      driver: json-file
    cap_add:
       - SYS_PTRACE
    depends_on:
      - db
    volumes:
      - ../backend:/app
      - ./nginx:/etc/nginx/conf.d
      - ./supervisor:/etc/supervisor/conf.d
    ports:
      - 5003:80
      - "6003:22"
    dns:
      - "8.8.8.8"
    networks:
      vpsp5_backend:
        ipv4_address: "172.40.0.2"
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     vpsp5_backend:
  #       ipv4_address: "172.40.0.3"

volumes: 
  crud: {}

networks:
  vpsp5_backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
