version: '3.7'
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: crud_db
    restart: unless-stopped
    environment: 
      - MYSQL_ROOT_PASSWORD=tz@Tadpole4#
      - MYSQL_DATABASE=crud_db
      - MYSQL_USER=crud_user
      - MYSQL_PASSWORD=pass4Tadpole#
      - MYSQL_INITDB_SKIP_TZINFO=yes
      - TZ=Africa/Kampala
    volumes: 
      - crud_local:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
      - /tmp:/tmp
    ports:
      - "3360:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crud_backend
    restart: unless-stopped
    hostname: crud_backend
    logging:
      driver: json-file
    cap_add:
       - SYS_PTRACE
    volumes:
      - ../backend:/var/www
      - /etc/hosts:/etc/hosts
      - /tmp:/tmp
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - 5003:80
      - "6003:22"
    dns:
      - "8.8.8.8"
    depends_on:
      - db
    networks:
      crud_network:
        ipv4_address: "172.40.0.3"

  # frontend:
  #   image: node:14
  #   container_name: crud_frontend
  #   working_dir: /app
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ../frontend:/app
  #   command: sh -c "yarn install && yarn serve" # faster for development
  #   depends_on:
  #     - backend

  # redis:
  #   image: redis:latest
  #   container_name: crud_redis
  #   restart: unless-stopped
  #   ports:
  #     - "6380:6379"
  #   depends_on:
  #     - backend

  # adminer:
  #   image: adminer:4.8.1
  #   container_name: crud_adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8002:8080 # 5432
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: testemail@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: adminer@Tadpole4#
  #   depends_on:
  #     - db
  #   # networks:
  #   #   crud_network:
  #   #     ipv4_address: "172.40.0.5"

volumes: 
  crud_local:
    driver: local

networks:
  crud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
