version: "3.7"

services:
    # PHP-FPM - Service
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: crud_backend
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ../backend:/var/www
            - ../docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        dns:
          - "8.8.8.8"
        networks:
          - app-network
            # ipv4_address: "172.16.0.2"

    # NGINX - Service
    webserver:
        image: nginx:1.20.1
        container_name: crud_server
        # restart: unless-stopped
        tty: true
        ports:
            - "8100:80"
            - "8443:443"
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - app-network

    # MariaDB - Service
    db:
        image: mariadb:10.5.6
        container_name: crud_db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: crud_db
            MYSQL_ROOT_PASSWORD: el@Paco24#
            TZ: Africa/Kampala
        volumes:
            - mariadbdata:/var/lib/mysql
            - ../docker-files/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    vuejs:
        image: node:14
        container_name: crud_frontend
        working_dir: /app
        ports:
            - "8081:8080"
        volumes:
            - ../frontend:/app
        command: sh -c "yarn install && yarn serve" # faster for development
        networks:
          - app-network

    # # Db Manager - Service
    # adminer:
    #     image: adminer:4.8.1
    #     container_name: crud_adminer
    #     restart: unless-stopped
    #     ports:
    #         - 8002:8080 # 5432
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: allandavicham@gmail.com
    #         PGADMIN_DEFAULT_PASSWORD: 12345678
    #     networks:
    #         app-network:
    #           ipv4_address: "172.16.0.5"

    # redis:
    #     image: redis:latest
    #     container_name: redis
    #     restart: always
    #     ports:
    #     - "6379:6379"
    #     networks:
    #     vpsp5_backend:
    #         ipv4_address: "172.40.0.3"


# Volumes
volumes:
    mariadbdata:
        driver: local

# Networks
networks:
  app-network:
      driver: bridge